steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.x'
  - name: Install dependencies
    run: pip install slack_sdk
  - name: Run Slack notification script
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    run: |
      echo "Sending notification to Slack"
      python -c 'import os; from slack_sdk import WebClient; from slack_sdk.errors import SlackApiError; slack_token = os.environ["SLACK_BOT_TOKEN"]; client = WebClient(token=slack_token); try: response = client.chat_postMessage(channel="#all-robocoder", text="hard af from GitHub Actions!"); print(f"Message sent: {response['ts']}") except SlackApiError as e: print(f"Error sending message: {e}")'
